spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/limites
    hikari:
      username: limits
      password: JpaLimitsSpringData
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      # hibernate.ddl-auto: create-drop # - Does not use in real production server.
      ddl-auto: update
      generate-ddl: true
      show-sql: true
    generate-ddl: true
  application:
    name: limite-svc

limite:
  valor: 2000