spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: limites-svc
      key-serializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
      enable-auto-commit: true # true -> atualizar o índice do offset automaticamente.

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/limites
    hikari:
      username: limits
      password: JpaLimitsSpringData
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    hibernate:
      # hibernate.ddl-auto: create-drop # - Does not use in real production server.
      ddl-auto: update
      generate-ddl: true
      show-sql: true
    generate-ddl: true
  application:
    name: limite-svc

limite:
  valor: 2000

app:
  topic: transaction
  returnTopic: transaction_extorno


server:
  port: 8086